steps:

# Build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops-dev', '.']

# Push the container image to Google Container Registry
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops-dev']

# Deploy the container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops-dev:latest
  - --location=europe-north1-a
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-dev


options:
  logging: CLOUD_LOGGING_ONLY
